export const products = [
  // Jamones
  {
    id: "jam1",
    name: "Jamón Ibérico de Bellota",
    description: "Jamón ibérico de bellota 100% raza ibérica con 36 meses de curación.",
    price: 89.95,
    format: "Pieza 7-8kg",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/jamon-iberico-bellota-riscales.jpg",
    category: "Jamones",
  },
  {
    id: "jam2",
    name: "Jamón Serrano Gran Reserva",
    description: "Jamón serrano de gran reserva con 24 meses de curación.",
    price: 59.95,
    format: "Pieza 6-7kg",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/jamon-serrano-riscales.jpg",
    category: "Jamones",
  },
  {
    id: "jam3",
    name: "Paleta Ibérica de Cebo",
    description: "Paleta ibérica de cebo con 24 meses de curación.",
    price: 45.95,
    format: "Pieza 4-5kg",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/paleta-iberica-riscales.jpg",
    category: "Jamones",
  },

  // Embutidos
  {
    id: "emb1",
    name: "Chorizo Ibérico de Bellota",
    description: "Chorizo ibérico elaborado con carnes seleccionadas de cerdo ibérico.",
    price: 12.95,
    format: "Pieza 500g",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/chorizo-iberico-riscales.jpg",
    category: "Embutidos",
  },
  {
    id: "emb2",
    name: "Salchichón Ibérico",
    description: "Salchichón ibérico elaborado de forma tradicional.",
    price: 11.95,
    format: "Pieza 500g",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/salchichon-iberico-riscales.jpg",
    category: "Embutidos",
  },
  {
    id: "emb3",
    name: "Lomo Ibérico de Bellota",
    description: "Lomo ibérico de bellota 100% natural.",
    price: 19.95,
    format: "Pieza 600g",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/lomo-iberico-riscales.jpg",
    category: "Embutidos",
  },

  // Quesos
  {
    id: "que1",
    name: "Queso Manchego Curado",
    description: "Queso manchego curado elaborado con leche cruda de oveja.",
    price: 15.95,
    format: "Pieza 1kg",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/queso-manchego-riscales.jpg",
    category: "Quesos",
  },
  {
    id: "que2",
    name: "Queso de Cabra al Romero",
    description: "Queso de cabra semicurado con romero.",
    price: 12.95,
    format: "Pieza 800g",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/queso-cabra-riscales.jpg",
    category: "Quesos",
  },
  {
    id: "que3",
    name: "Queso Azul de Valdeón",
    description: "Queso azul de Valdeón elaborado con leche pasteurizada de vaca y cabra.",
    price: 14.95,
    format: "Pieza 500g",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/queso-azul-riscales.jpg",
    category: "Quesos",
  },

  // Aceites
  {
    id: "ace1",
    name: "Aceite de Oliva Virgen Extra",
    description: "Aceite de oliva virgen extra de primera presión en frío.",
    price: 9.95,
    format: "Botella 500ml",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/aceite-oliva-riscales.jpg",
    category: "Aceites",
  },
  {
    id: "ace2",
    name: "Aceite de Oliva Virgen Extra Ecológico",
    description: "Aceite de oliva virgen extra ecológico de producción sostenible.",
    price: 12.95,
    format: "Botella 500ml",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/aceite-ecologico-riscales.jpg",
    category: "Aceites",
  },
  {
    id: "ace3",
    name: "Aceite de Oliva Virgen Extra Arbequina",
    description: "Aceite de oliva virgen extra variedad arbequina.",
    price: 11.95,
    format: "Botella 500ml",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/aceite-arbequina-riscales.jpg",
    category: "Aceites",
  },

  // Conservas gourmet
  {
    id: "con1",
    name: "Anchoas del Cantábrico",
    description: "Anchoas del Cantábrico en aceite de oliva.",
    price: 14.95,
    format: "Lata 50g",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/anchoas-riscales.jpg",
    category: "Conservas gourmet",
  },
  {
    id: "con2",
    name: "Bonito del Norte",
    description: "Bonito del Norte en aceite de oliva.",
    price: 12.95,
    format: "Lata 190g",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/bonito-riscales.jpg",
    category: "Conservas gourmet",
  },
  {
    id: "con3",
    name: "Paté de Perdiz",
    description: "Paté artesano de perdiz.",
    price: 8.95,
    format: "Tarro 180g",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/pate-perdiz-riscales.jpg",
    category: "Conservas gourmet",
  },

  // Vinos
  {
    id: "vin1",
    name: "Vino Tinto Ribera del Duero Crianza",
    description: "Vino tinto Ribera del Duero crianza.",
    price: 15.95,
    format: "Botella 75cl",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/vino-ribera-riscales.jpg",
    category: "Vinos",
  },
  {
    id: "vin2",
    name: "Vino Blanco Albariño",
    description: "Vino blanco Albariño D.O. Rías Baixas.",
    price: 13.95,
    format: "Botella 75cl",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/vino-albarino-riscales.jpg",
    category: "Vinos",
  },
  {
    id: "vin3",
    name: "Vino Tinto Rioja Reserva",
    description: "Vino tinto Rioja reserva.",
    price: 18.95,
    format: "Botella 75cl",
    image: "https://www.riscalesalimentacion.com/wp-content/uploads/2022/01/vino-rioja-riscales.jpg",
    category: "Vinos",
  },
]

